### ISSUE TITLE
Parity Data

### ISSUE THREAD

**Issue by tillvit** [mjvotaw/tech-counts-editor#1]
Hi there, saw your forks on trying to collect parity data to adjust the weights and thought I'd contribute with some RIP 13.5 files I annotated. The keys are formatted as "smfile^chartindex", and the foot placement data consists of rows of L/R (no foot/heel data), separated by "|". If a row contains an arrow on row 2 and 3, and the data is RL, then the right foot is on down and left foot is on up.
[parity.txt](https://github.com/user-attachments/files/16720646/parity.txt)

Good luck with the project! Let me know if you have any problems with the data. (feel free to close the issue when you got the data)

**Comment by mjvotaw** [comment]
Hey, thanks! Yeah overall, the project has been mostly successful. I've been able to catch a handful of small errors in the parity generation, and  teej and I are working on refining how the actual tech counts work https://github.com/itgmania/itgmania/pull/369

I don't think any of this progress would have been possible without SMEditor. Having a tool to hack away at and help me quickly visualize things has made this so much easier.

**Comment by tillvit** [comment]
No problem! Sorry for the somewhat messy codebase haha.
